### ISSUE TITLE
llvm-go tests broken

### ISSUE THREAD

**Issue by riptl** [anza-xyz/llvm-project#33]
## Problem

It looks like GitHub's ubuntu-2004 virtual environment has upgraded the pre-installed Go package to Go 1.16+.

This causes `llvm check-all` to fail on branch `solana-rustc/13.0-2021-09-30`: https://github.com/solana-labs/llvm-project/runs/6041800180?check_suite_focus=true#step:5:4480

## Suggested fixes

- Cherry-pick the fix from upstream llvm-project
- Install golang-1.15 from APT and use `update-alternatives` to override `/usr/bin/go`

**Comment by dmakarov** [comment]
What would be the specific fix to cherry-pick from the upstream?

**Comment by riptl** [comment]
@dmakarov I'm not aware of any specific fix. I assumed there was one but I've done a quick check and couldn't find anything.

**Comment by dmakarov** [comment]
> @dmakarov I'm not aware of any specific fix. I assumed there was one but I've done a quick check and couldn't find anything.

I couldn't find it either. I'm not sure I want to mess with update-alternatives. I'll disable the Go bindings tests for now. We'll soon move to llvm-14, so it shouldn't matter, unless this is also somehow broken there too.

**Comment by dmakarov** [comment]
This is fixed for now by #34
