### ISSUE TITLE
Missing instruction unit tests for sdiv32 and sdiv64

### ISSUE THREAD

**Issue by riptl** [anza-xyz/llvm-project#47]
https://github.com/solana-labs/llvm-project/blob/solana-rustc/13.0-2021-09-30/llvm/test/MC/BPF/insn-unit.s

lacks

- sdiv32 rD, imm (0xe4)
- sdiv32 rD, rS (0xec)
- sdiv64 rD, imm (0xe7)
- sdiv64 rD, rS (0xef)

**Comment by nvjle** [comment]
This is no longer an issue-- the SBF back-end now provides tests for `sdiv32` and `sdiv64`. Closing.
